all:
  vars:
    ansible_ssh_private_key_file: ~/.ssh/tfm_proxmox_temp_2026
  children:
    gitea_runner:
      hosts:
        gitea:
          ansible_host: 192.168.1.211
          ansible_user: root
    vault_servers:
      hosts:
        vault:
          ansible_host: 192.168.1.220
          ansible_user: root
    postgres_servers:
      hosts:
        postgres:
          ansible_host: 192.168.1.230
          ansible_user: root
    k3s_servers:
      hosts:
        k3s:
          ansible_host: 192.168.1.240
          ansible_user: debian
